from pathlib import Path
import json

p=Path('app/src/main/assets/www/index.html')
s=p.read_text(encoding='utf-8')
rules=json.loads(Path('rules/dzen-rules.json').read_text(encoding='utf-8'))
rules_js=json.dumps(rules,ensure_ascii=False,separators=(',',':'))

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'Patch anchor not found: {label}')
    s=s.replace(old,new,1)

rep('<title>Дзен Текст 1.3.5</title>','<title>Дзен Текст 1.4.0</title>','title')

css_anchor='.fileInput{display:none}.dictStatus{font-size:12px;color:var(--muted);margin:7px 0 8px}.dictStatus b{color:var(--text)}'
css_extra='''.analysisSheet{transition:max-height .18s ease,bottom .18s ease,left .18s ease,right .18s ease}.analysisHeader{display:flex;align-items:center;gap:10px}.analysisHeader h2{flex:1;margin:0 0 15px}.analysisCollapse{width:38px;height:38px;border:1px solid var(--border);border-radius:10px;background:var(--surface2);color:var(--text);font-size:22px;display:grid;place-items:center;margin-bottom:12px}.analysisFilters{display:flex;gap:6px;margin:0 0 12px;overflow-x:auto;scrollbar-width:none}.analysisFilters::-webkit-scrollbar{display:none}.analysisFilter{border:1px solid var(--border);background:var(--surface2);color:var(--text);border-radius:999px;padding:7px 11px;font-size:12px;font-weight:700;white-space:nowrap}.analysisFilter.active{border-color:var(--accent);background:var(--accentSoft);color:var(--accent)}.analysisCollapsedSummary{display:none;color:var(--muted);font-size:12px;line-height:1.35;margin-top:-8px}.sheetBackdrop.collapsed{background:transparent;pointer-events:none}.sheetBackdrop.collapsed .analysisSheet{left:10px;right:10px;bottom:68px;border-radius:16px;max-height:none;padding:11px 13px;pointer-events:auto;box-shadow:0 8px 28px rgba(0,0,0,.2)}.sheetBackdrop.collapsed .analysisSheet>.handle,.sheetBackdrop.collapsed .analysisFilters,.sheetBackdrop.collapsed #analysisBody{display:none}.sheetBackdrop.collapsed .analysisHeader h2{font-size:15px;margin:0}.sheetBackdrop.collapsed .analysisCollapse{margin:0;width:34px;height:34px}.sheetBackdrop.collapsed .analysisCollapsedSummary{display:block;margin:3px 44px 0 0}.analysisRow.dzenRisk .warn{color:#b26718}.analysisDzenNote{background:var(--surface2);border-radius:11px;padding:10px 11px;color:var(--muted);font-size:12px;line-height:1.45;margin:8px 0}.analysisDzenNote b{color:var(--text)}.manualChecklist{margin:7px 0 0;padding-left:18px}.manualChecklist li{margin:5px 0}.ruleStatus{font-size:12px;line-height:1.45;color:var(--muted);margin:8px 0}.ruleStatus b{color:var(--text)}\n'''
rep(css_anchor,css_extra+css_anchor,'analysis v1.4 css')

settings_anchor='''    <div class="switchRow" style="margin-top:13px"><span>Большие участки без подзаголовков</span><input id="structureCheck" class="switch" type="checkbox" onchange="applySettings()"></div><div class="subLabel"><span>Порог</span><span class="val" id="structureVal"></span></div><input id="structureMax" type="range" min="800" max="3500" step="100" oninput="applySettings()">\n  </details></div>'''
settings_new='''    <div class="switchRow" style="margin-top:13px"><span>Большие участки без подзаголовков</span><input id="structureCheck" class="switch" type="checkbox" onchange="applySettings()"></div><div class="subLabel"><span>Порог</span><span class="val" id="structureVal"></span></div><input id="structureMax" type="range" min="800" max="3500" step="100" oninput="applySettings()">\n    <div class="switchRow" style="margin-top:13px"><span>Повторяющиеся фразы</span><input id="phraseCheck" class="switch" type="checkbox" onchange="applySettings()"></div>\n    <div class="switchRow" style="margin-top:13px"><span>Одинаковые начала предложений и абзацев</span><input id="openingCheck" class="switch" type="checkbox" onchange="applySettings()"></div>\n    <div class="switchRow" style="margin-top:13px"><span>Структура H1–H3</span><input id="headingStructureCheck" class="switch" type="checkbox" onchange="applySettings()"></div>\n    <div class="switchRow" style="margin-top:13px"><span>Ошибки Markdown</span><input id="markdownCheck" class="switch" type="checkbox" onchange="applySettings()"></div>\n  </details></div>'''
rep(settings_anchor,settings_new,'new editor checks')

syn_anchor='  <div class="setting"><details><summary>Словарь синонимов</summary>'
dzen_settings='''  <div class="setting"><details><summary>Правила Дзена</summary>\n    <div class="switchRow"><span>Проверять возможные риски</span><input id="dzenCheck" class="switch" type="checkbox" onchange="applySettings()"></div>\n    <div class="smallNote">Это предварительная эвристическая проверка. Она не заменяет модерацию Дзена и не объявляет совпадение нарушением.</div>\n    <div id="dzenRulesStatus" class="ruleStatus"></div>\n    <div class="settingActions"><button class="nativeBtn" type="button" onclick="updateDzenRulesFromGitHub()">Проверить обновление</button><button class="nativeBtn" type="button" onclick="resetDzenRules()">Вернуть встроенные</button></div>\n    <div class="smallNote">Обновление загружается только по кнопке с GitHub-репозитория dzen-text. Встроенная база работает офлайн.</div>\n  </details></div>\n'''+syn_anchor
rep(syn_anchor,dzen_settings,'Dzen settings')

analysis_old='''<div class="sheetBackdrop" id="analysisBackdrop" onclick="analysisBackdropClick(event)"><div class="sheet">\n  <div class="handle"></div><h2>Редакторский анализ</h2><div id="analysisSummary" class="analysisSummary"></div><div id="analysisContent"></div>\n</div></div>'''
analysis_new='''<div class="sheetBackdrop" id="analysisBackdrop" onclick="analysisBackdropClick(event)"><div class="sheet analysisSheet">\n  <div class="handle"></div><div class="analysisHeader"><h2>Редакторский анализ</h2><button id="analysisCollapse" class="analysisCollapse" type="button" onclick="toggleAnalysisCollapse()" aria-label="Свернуть анализ">⌄</button></div><div id="analysisCollapsedSummary" class="analysisCollapsedSummary"></div>\n  <div class="analysisFilters"><button class="analysisFilter active" data-mode="problems" onclick="setAnalysisMode('problems')">Только проблемы</button><button class="analysisFilter" data-mode="all" onclick="setAnalysisMode('all')">Всё</button><button class="analysisFilter" data-mode="dzen" onclick="setAnalysisMode('dzen')">Правила Дзена</button></div>\n  <div id="analysisBody"><div id="analysisSummary" class="analysisSummary"></div><div id="analysisContent"></div></div>\n</div></div>'''
rep(analysis_old,analysis_new,'analysis sheet markup')

old_defaults="const defaultSettings={font:'system',size:18,line:1.65,theme:'system',wpm:200,tts:1.0,autosave:true,showCode:false,headingCheck:true,headingMin:8,headingMax:80,sentenceCheck:true,sentenceMax:30,paragraphCheck:true,paragraphMax:650,frequentCheck:true,frequentMin:8,nearbyCheck:true,structureCheck:true,structureMax:1800,riskCheck:true,riskWords:exampleRiskWords};"
new_defaults="const defaultSettings={font:'system',size:18,line:1.65,theme:'system',wpm:200,tts:1.0,autosave:true,showCode:false,headingCheck:true,headingMin:8,headingMax:80,sentenceCheck:true,sentenceMax:30,paragraphCheck:true,paragraphMax:650,frequentCheck:true,frequentMin:8,nearbyCheck:true,structureCheck:true,structureMax:1800,phraseCheck:true,openingCheck:true,headingStructureCheck:true,markdownCheck:true,dzenCheck:true,riskCheck:true,riskWords:exampleRiskWords};"
rep(old_defaults,new_defaults,'default settings')

state_anchor="const USER_SYNONYMS_KEY='dzenUserSynonymsV1';\nlet userSynonyms=loadUserSynonyms();"
state_new=state_anchor+f'''\nconst DZEN_RULES_URL='https://raw.githubusercontent.com/Ayuemin/dzen-text/main/rules/dzen-rules.json';\nconst DZEN_RULES_KEY='dzenRulesV1';\nconst DEFAULT_DZEN_RULES={rules_js};\nlet dzenRulesFromCache=false;\nlet dzenRules=loadDzenRules();\nfunction validDzenRules(o){{return !!(o&&Number(o.schema)===1&&Number(o.article_title_max_chars)>0&&Array.isArray(o.manual_checks))}}\nfunction loadDzenRules(){{try{{const raw=localStorage.getItem(DZEN_RULES_KEY);if(raw){{const o=JSON.parse(raw);if(validDzenRules(o)){{dzenRulesFromCache=true;return o}}}}}}catch(e){{}}return DEFAULT_DZEN_RULES}}\nfunction updateDzenRulesStatus(){{const el=document.getElementById('dzenRulesStatus');if(!el)return;el.innerHTML=`База правил: <b>${{escapeHtml(String(dzenRules.version||'встроенная'))}}</b> · ${{dzenRulesFromCache?'обновлённая':'встроенная'}}<br>Источник проверен: ${{escapeHtml(String(dzenRules.source_checked||'—'))}}`}}\nasync function updateDzenRulesFromGitHub(){{const el=document.getElementById('dzenRulesStatus');if(el)el.textContent='Проверяю обновление…';try{{const r=await fetch(DZEN_RULES_URL+'?t='+Date.now(),{{cache:'no-store'}});if(!r.ok)throw new Error('HTTP '+r.status);const o=await r.json();if(!validDzenRules(o))throw new Error('Некорректный формат');localStorage.setItem(DZEN_RULES_KEY,JSON.stringify(o));dzenRules=o;dzenRulesFromCache=true;updateDzenRulesStatus();render();toast(`Правила Дзена обновлены: ${{o.version||'новая версия'}}`)}}catch(e){{updateDzenRulesStatus();toast('Не удалось обновить правила. Встроенная база продолжает работать')}}}}\nfunction resetDzenRules(){{localStorage.removeItem(DZEN_RULES_KEY);dzenRules=DEFAULT_DZEN_RULES;dzenRulesFromCache=false;updateDzenRulesStatus();render();toast('Восстановлена встроенная база правил Дзена')}}'''
rep(state_anchor,state_new,'Dzen rules state')

helpers=r'''
function addSimpleIssue(issues,type,title,detail,start,end,severity='warning'){addIssue(issues,type,title,detail,Math.max(0,start||0),Math.max(Math.max(0,start||0),end||start||0),severity)}
function analyzeRepeatedPhrases(src,issues){const ws=wordMatches(src).map(m=>({text:m[0],low:m[0].toLocaleLowerCase('ru-RU'),start:m.index,end:m.index+m[0].length})),maps={3:new Map(),2:new Map()};for(const n of [3,2]){for(let i=0;i+n<=ws.length;i++){const a=ws.slice(i,i+n),segment=src.slice(a[0].start,a[a.length-1].end);if(/[.!?…\n]/.test(segment))continue;if(n===2&&(a.some(x=>x.low.length<5||stopWords.has(x.low))))continue;if(n===3&&a.filter(x=>x.low.length>=4&&!stopWords.has(x.low)).length<2)continue;const key=a.map(x=>x.low).join(' ');if(key.length<10)continue;let v=maps[n].get(key);if(!v){v={count:0,start:a[0].start,end:a[a.length-1].end,text:segment};maps[n].set(key,v)}v.count++}}const selected=[];for(const n of [3,2]){const arr=[...maps[n].entries()].filter(([,v])=>v.count>=2).sort((a,b)=>b[1].count-a[1].count||b[0].length-a[0].length);for(const [key,v] of arr){if(selected.length>=8)break;if(n===2&&selected.some(x=>x.key.includes(key)))continue;selected.push({key,...v});addSimpleIssue(issues,'phrase',`Повторяется фраза: «${v.text}»`,`${v.count} раза в тексте`,v.start,v.end)}}}
function analyzeOpenings(sentences,paragraphs,issues){const scan=(items,label,minCount)=>{const map=new Map();for(const o of items){const m=wordMatches(stripMarkdownForLabel(o.text))[0];if(!m)continue;const key=m[0].toLocaleLowerCase('ru-RU');if(key.length<3)continue;let v=map.get(key);if(!v){const local=o.text.toLocaleLowerCase('ru-RU').indexOf(key);v={count:0,start:o.start+Math.max(0,local),end:o.start+Math.max(0,local)+m[0].length,word:m[0]};map.set(key,v)}v.count++}for(const [,v] of [...map].filter(([,v])=>v.count>=minCount).sort((a,b)=>b[1].count-a[1].count).slice(0,5)){addSimpleIssue(issues,'opening',`${label} часто начинаются с «${v.word}»`,`${v.count} одинаковых начал`,v.start,v.end)}};scan(sentences,'Предложения',3);scan(paragraphs,'Абзацы',3)}
function analyzeHeadingStructure(src,headings,issues){const h1=headings.filter(h=>h.level===1);for(let i=1;i<h1.length;i++)addSimpleIssue(issues,'headingStructure','Несколько заголовков H1','Обычно основной заголовок статьи один',h1[i].start,h1[i].end);for(let i=1;i<headings.length;i++){const p=headings[i-1],h=headings[i];if(h.level>p.level+1)addSimpleIssue(issues,'headingStructure',`Скачок H${p.level} → H${h.level}`,'Уровень заголовка пропущен',h.start,h.end);const prevLineEnd=src.indexOf('\n',p.lineStart);if(prevLineEnd>=0&&src.slice(prevLineEnd+1,h.lineStart).trim()==='')addSimpleIssue(issues,'headingStructure','Два заголовка подряд','Между заголовками нет обычного текста',h.start,h.end)}}
function analyzeMarkdown(src,issues){for(const [mark,name] of [['**','**'],['__','__'],['~~','~~'],['`','`']]){let c=0,pos=-1,i=0;while((i=src.indexOf(mark,i))!==-1){c++;pos=i;i+=mark.length}if(c%2)addSimpleIssue(issues,'markdown',`Незакрытая разметка ${name}`,'Проверьте парный маркер Markdown',pos,pos+mark.length)}for(const m of src.matchAll(/^#{1,6}[^#\s].*$/gm))addSimpleIssue(issues,'markdown','После # нужен пробел','Заголовок Markdown может не распознаться',m.index,m.index+m[0].length);for(const m of src.matchAll(/\[[^\]\n]+\]\([^\)\n]*$/gm))addSimpleIssue(issues,'markdown','Незакрытая Markdown-ссылка','Не найдена закрывающая скобка )',m.index,m.index+m[0].length)}
function analyzeDzenRules(src,headings,issues){const lower=src.toLocaleLowerCase('ru-RU'),r=dzenRules||DEFAULT_DZEN_RULES,titleObj=headings.find(h=>h.level===1),title=titleObj?titleObj.text:'';if(titleObj&&title.length>Number(r.article_title_max_chars||140))addSimpleIssue(issues,'dzen',`Заголовок длиннее ${r.article_title_max_chars} знаков`,`${title.length} знаков — проверьте лимит статьи Дзена`,titleObj.start,titleObj.end,'critical');if(titleObj){const tl=title.toLocaleLowerCase('ru-RU');for(const ph of r.clickbait_phrases||[]){const q=String(ph).toLocaleLowerCase('ru-RU'),at=tl.indexOf(q);if(at>=0){addSimpleIssue(issues,'dzen','Возможный кликбейт в заголовке',`Найдена формулировка «${ph}». Важно, чтобы заголовок точно соответствовал содержанию`,titleObj.start+at,titleObj.start+at+q.length);break}}const letters=Array.from(title).filter(c=>/[A-Za-zА-Яа-яЁё]/.test(c));const upp=letters.filter(c=>c===c.toUpperCase()&&c!==c.toLowerCase()).length;if(letters.length>=10&&upp/letters.length>.55)addSimpleIssue(issues,'dzen','Много ЗАГЛАВНЫХ букв в заголовке','Может выглядеть как агрессивное оформление карточки',titleObj.start,titleObj.end);if(/[!?]{2,}/.test(title))addSimpleIssue(issues,'dzen','Повторяющиеся !/? в заголовке','Проверьте, не создаёт ли оформление ложного ожидания',titleObj.start,titleObj.end)}const addPhraseList=(arr,titleText,severity='warning')=>{let shown=0;for(const ph of arr||[]){const q=String(ph).toLocaleLowerCase('ru-RU'),at=lower.indexOf(q);if(at>=0){addSimpleIssue(issues,'dzen',titleText,`Найдена фраза «${ph}». Оцените её в контексте`,at,at+q.length,severity);if(++shown>=4)break}}};addPhraseList(r.dangerous_phrases,'Опасная или незаконная тематика — проверить контекст','critical');addPhraseList(r.medical_claim_phrases,'Категоричное медицинское утверждение — проверить','warning');let prof=0;for(const stem of r.profanity_stems||[]){const at=lower.indexOf(String(stem).toLocaleLowerCase('ru-RU'));if(at>=0){addSimpleIssue(issues,'dzen','Возможная ненормативная лексика',`Найден фрагмент «${src.slice(at,Math.min(src.length,at+Math.max(6,String(stem).length+3)))}…»`,at,Math.min(src.length,at+String(stem).length),'critical');if(++prof>=3)break}}const urls=Array.from(src.matchAll(/https?:\/\/[^\s)]+/g));if(urls.length>10)addSimpleIssue(issues,'dzen','Много ссылок в публикации',`${urls.length} ссылок — проверьте, не выглядит ли материал как ссылочный спам`,urls[10].index,urls[10].index+urls[10][0].length);const um=new Map();for(const u of urls){const k=u[0].replace(/[.,!?]+$/,'');let v=um.get(k)||{count:0,start:u.index,end:u.index+u[0].length};v.count++;um.set(k,v)}for(const [url,v] of um){if(v.count>=3){addSimpleIssue(issues,'dzen','Одна и та же ссылка повторяется',`${v.count} повторов одного URL`,v.start,v.end);break}}}
'''
pos=s.index('function analyzeText(){')
s=s[:pos]+helpers+s[pos:]

analysis_calls=""" if(settings.headingStructureCheck)analyzeHeadingStructure(src,headings,issues);\n if(settings.phraseCheck)analyzeRepeatedPhrases(src,issues);\n if(settings.openingCheck)analyzeOpenings(sentences,paragraphs,issues);\n if(settings.markdownCheck)analyzeMarkdown(src,issues);\n if(settings.dzenCheck)analyzeDzenRules(src,headings,issues);\n"""
rep(' const html=markdownToHtml(src),plain=plainFromHtml(html);',analysis_calls+' const html=markdownToHtml(src),plain=plainFromHtml(html);','new analysis calls')
rep(' const warningCount=issues.length;currentAnalysis={issues,warningCount,metrics};renderAnalysis();updateAnalysisDot();return currentAnalysis}'," const warningCount=issues.length,dzenCount=issues.filter(x=>x.type==='dzen').length,editorCount=warningCount-dzenCount;currentAnalysis={issues,warningCount,dzenCount,editorCount,metrics};renderAnalysis();updateAnalysisDot();return currentAnalysis}",'analysis counts')

a=s.index('function updateAnalysisDot()')
b=s.index('function jumpTo(',a)
new_render=r'''function updateAnalysisDot(){const dot=document.getElementById('analysisDot');dot.classList.toggle('bad',currentAnalysis.warningCount>0);dot.setAttribute('aria-label',currentAnalysis.warningCount?`Есть замечания: ${currentAnalysis.warningCount}`:'Замечаний нет');dot.title=currentAnalysis.warningCount?`Есть замечания: ${currentAnalysis.warningCount}`:'Всё в пределах настроенных норм'}
function issueGroups(){return [{id:'risk',name:'Контроль слов'},{id:'dzen',name:'Правила Дзена'},{id:'heading',name:'Заголовки'},{id:'headingStructure',name:'Структура H1–H3'},{id:'sentence',name:'Длинные предложения'},{id:'paragraph',name:'Длинные абзацы'},{id:'frequent',name:'Частые слова'},{id:'nearby',name:'Повторы рядом'},{id:'phrase',name:'Повторяющиеся фразы'},{id:'opening',name:'Одинаковые начала'},{id:'markdown',name:'Markdown'},{id:'structure',name:'Структура текста'}]}
let analysisMode='problems';
function setAnalysisMode(mode){analysisMode=['problems','all','dzen'].includes(mode)?mode:'problems';document.querySelectorAll('.analysisFilter').forEach(b=>b.classList.toggle('active',b.dataset.mode===analysisMode));renderAnalysis()}
function renderDzenManual(){const items=(dzenRules.manual_checks||[]).map(x=>`<li>${escapeHtml(String(x))}</li>`).join('');return `<div class="analysisDzenNote"><b>Что приложение не может подтвердить автоматически</b><ul class="manualChecklist">${items}</ul></div>`}
function renderAnalysis(){const box=document.getElementById('analysisContent'),sum=document.getElementById('analysisSummary'),collapsed=document.getElementById('analysisCollapsedSummary'),a=currentAnalysis,ec=a.editorCount||0,dc=a.dzenCount||0;sum.innerHTML=a.warningCount?`Редакторских замечаний: <b>${ec}</b> · по правилам Дзена: <b>${dc}</b>.`:'<b>По включённым автоматическим проверкам замечаний нет.</b> Финальная вычитка всё равно нужна.';if(collapsed)collapsed.textContent=`${ec?'🔴':'🟢'} редакторских: ${ec} · ${dc?'🟠':'🟢'} Дзен: ${dc}`;document.querySelectorAll('.analysisFilter').forEach(b=>b.classList.toggle('active',b.dataset.mode===analysisMode));let html='';if(analysisMode==='all')html+=`<div class="analysisInfo"><div class="metric"><b>${a.metrics.headings?.length||0}</b><span>заголовков</span></div><div class="metric"><b>${a.metrics.avgSentence||0}</b><span>слов в среднем предложении</span></div><div class="metric"><b>${a.metrics.lists||0}</b><span>пунктов списков</span></div><div class="metric"><b>${a.metrics.links||0}</b><span>ссылок</span></div></div>`;if(analysisMode==='dzen'){const rows=a.issues.filter(x=>x.type==='dzen');html+=`<div class="analysisDzenNote">База правил: <b>${escapeHtml(String(dzenRules.version||'встроенная'))}</b>. Совпадение означает только повод проверить фрагмент, а не установленное нарушение.</div>`;if(rows.length)html+=`<div class="analysisGroup"><div class="analysisTitle"><span>Возможные риски</span><span class="badge bad">${rows.length}</span></div>${rows.map(issueHtml).join('')}</div>`;else html+='<div class="analysisEmpty">Автоматические признаки риска по текущей базе не найдены.</div>';html+=renderDzenManual();box.innerHTML=html;return}for(const g of issueGroups()){const rows=a.issues.filter(x=>x.type===g.id);if(g.id==='heading'&&analysisMode==='all'){const hs=a.metrics.headings||[];html+=`<div class="analysisGroup"><div class="analysisTitle"><span>${g.name}</span><span class="badge ${rows.length?'bad':''}">${rows.length||'✓'}</span></div>`;if(!hs.length)html+='<div class="analysisRow"><span class="meta">Заголовков Markdown не найдено.</span></div>';else for(const h of hs){const bad=rows.find(r=>r.start===h.start);html+=bad?issueHtml(bad):`<button class="analysisRow jump" onclick="jumpTo(${h.start},${h.end})"><span class="ok">H${h.level} · ${h.text.length} знаков</span> ${escapeHtml(h.text)}<span class="meta">Нажмите, чтобы перейти к заголовку</span></button>`}html+='</div>';continue}if(!rows.length)continue;html+=`<div class="analysisGroup"><div class="analysisTitle"><span>${g.name}</span><span class="badge bad">${rows.length}</span></div>${rows.map(issueHtml).join('')}</div>`}if(!a.warningCount)html+='<div class="analysisEmpty">Красных замечаний нет. Переключите «Всё», чтобы посмотреть информационные показатели.</div>';box.innerHTML=html}
function issueHtml(i){let sev=i.severity==='critical'?'Контроль':'Обратите внимание';if(i.type==='dzen')sev=i.severity==='critical'?'Высокий риск — проверить':'Проверить вручную';const word=i.word?String(i.word):'';let click,cls,hint;if(i.type==='nearby'&&Number.isFinite(i.pairStart)){click=`openNearbyRepeat(${i.pairStart},${i.pairEnd},${i.start},${i.end},${i.firstSentenceStart},${i.firstSentenceEnd},${i.secondSentenceStart},${i.secondSentenceEnd},${JSON.stringify(word)})`;cls='analysisRow jump nearbyWord';hint='нажмите: показать оба повтора'}else{click=word&&i.type==='frequent'?`openReplacement(${i.start},${i.end},${JSON.stringify(word)})`:`jumpTo(${i.start},${i.end})`;cls='analysisRow jump'+(word&&i.type==='frequent'?' frequentWord':'')+(i.type==='dzen'?' dzenRisk':'');hint=word&&i.type==='frequent'?'нажмите: перейти и выбрать замену':'нажмите для перехода'}return `<button class="${cls}" onclick='${click.replace(/'/g,"&#39;")}'><span class="warn">${escapeHtml(i.title)}</span><span class="meta">${escapeHtml(i.detail||'')} · ${sev} · ${hint}</span></button>`}
function toggleAnalysisCollapse(){const bd=document.getElementById('analysisBackdrop'),btn=document.getElementById('analysisCollapse'),on=bd.classList.toggle('collapsed');btn.textContent=on?'⌃':'⌄';btn.setAttribute('aria-label',on?'Развернуть анализ':'Свернуть анализ')}
function openAnalysis(){analyzeText();const bd=document.getElementById('analysisBackdrop');bd.classList.add('open');bd.classList.remove('collapsed');const btn=document.getElementById('analysisCollapse');if(btn){btn.textContent='⌄';btn.setAttribute('aria-label','Свернуть анализ')}setAnalysisMode(analysisMode)}
function analysisBackdropClick(e){if(e.target.id==='analysisBackdrop'&&!e.currentTarget.classList.contains('collapsed'))e.currentTarget.classList.remove('open')}
'''
s=s[:a]+new_render+s[b:]

old_sync="function syncSettingsUI(){fontSelect.value=settings.font;sizeRange.value=settings.size;lineRange.value=settings.line;themeSelect.value=settings.theme;wpmRange.value=settings.wpm;ttsRange.value=settings.tts;autosaveSwitch.checked=settings.autosave;codeSwitch.checked=settings.showCode;headingCheck.checked=settings.headingCheck;headingMin.value=settings.headingMin;headingMax.value=settings.headingMax;sentenceCheck.checked=settings.sentenceCheck;sentenceMax.value=settings.sentenceMax;paragraphCheck.checked=settings.paragraphCheck;paragraphMax.value=settings.paragraphMax;frequentCheck.checked=settings.frequentCheck;frequentMin.value=settings.frequentMin;nearbyCheck.checked=settings.nearbyCheck;structureCheck.checked=settings.structureCheck;structureMax.value=settings.structureMax;riskCheck.checked=settings.riskCheck;riskWords.value=settings.riskWords||'';updateSettingLabels()}"
new_sync="function syncSettingsUI(){fontSelect.value=settings.font;sizeRange.value=settings.size;lineRange.value=settings.line;themeSelect.value=settings.theme;wpmRange.value=settings.wpm;ttsRange.value=settings.tts;autosaveSwitch.checked=settings.autosave;codeSwitch.checked=settings.showCode;headingCheck.checked=settings.headingCheck;headingMin.value=settings.headingMin;headingMax.value=settings.headingMax;sentenceCheck.checked=settings.sentenceCheck;sentenceMax.value=settings.sentenceMax;paragraphCheck.checked=settings.paragraphCheck;paragraphMax.value=settings.paragraphMax;frequentCheck.checked=settings.frequentCheck;frequentMin.value=settings.frequentMin;nearbyCheck.checked=settings.nearbyCheck;structureCheck.checked=settings.structureCheck;structureMax.value=settings.structureMax;phraseCheck.checked=settings.phraseCheck;openingCheck.checked=settings.openingCheck;headingStructureCheck.checked=settings.headingStructureCheck;markdownCheck.checked=settings.markdownCheck;dzenCheck.checked=settings.dzenCheck;riskCheck.checked=settings.riskCheck;riskWords.value=settings.riskWords||'';updateSettingLabels();updateDzenRulesStatus()}"
rep(old_sync,new_sync,'sync settings')

old_apply="function applySettings(){settings={...settings,font:fontSelect.value,size:+sizeRange.value,line:+lineRange.value,theme:themeSelect.value,wpm:+wpmRange.value,tts:+ttsRange.value,autosave:autosaveSwitch.checked,showCode:codeSwitch.checked,headingCheck:headingCheck.checked,headingMin:+headingMin.value,headingMax:+headingMax.value,sentenceCheck:sentenceCheck.checked,sentenceMax:+sentenceMax.value,paragraphCheck:paragraphCheck.checked,paragraphMax:+paragraphMax.value,frequentCheck:frequentCheck.checked,frequentMin:+frequentMin.value,nearbyCheck:nearbyCheck.checked,structureCheck:structureCheck.checked,structureMax:+structureMax.value,riskCheck:riskCheck.checked,riskWords:riskWords.value};if(settings.headingMin>=settings.headingMax)settings.headingMin=Math.max(3,settings.headingMax-5);localStorage.setItem('dzenSettings',JSON.stringify(settings));applyVisualSettings();render();updateSettingLabels()}"
new_apply="function applySettings(){settings={...settings,font:fontSelect.value,size:+sizeRange.value,line:+lineRange.value,theme:themeSelect.value,wpm:+wpmRange.value,tts:+ttsRange.value,autosave:autosaveSwitch.checked,showCode:codeSwitch.checked,headingCheck:headingCheck.checked,headingMin:+headingMin.value,headingMax:+headingMax.value,sentenceCheck:sentenceCheck.checked,sentenceMax:+sentenceMax.value,paragraphCheck:paragraphCheck.checked,paragraphMax:+paragraphMax.value,frequentCheck:frequentCheck.checked,frequentMin:+frequentMin.value,nearbyCheck:nearbyCheck.checked,structureCheck:structureCheck.checked,structureMax:+structureMax.value,phraseCheck:phraseCheck.checked,openingCheck:openingCheck.checked,headingStructureCheck:headingStructureCheck.checked,markdownCheck:markdownCheck.checked,dzenCheck:dzenCheck.checked,riskCheck:riskCheck.checked,riskWords:riskWords.value};if(settings.headingMin>=settings.headingMax)settings.headingMin=Math.max(3,settings.headingMax-5);localStorage.setItem('dzenSettings',JSON.stringify(settings));applyVisualSettings();render();updateSettingLabels()}"
rep(old_apply,new_apply,'apply settings')
rep("function openSettings(){syncSettingsUI();updateDictStatus();document.getElementById('settingsBackdrop').classList.add('open');setTimeout(updateDictStatus,120)}","function openSettings(){syncSettingsUI();updateDictStatus();updateDzenRulesStatus();document.getElementById('settingsBackdrop').classList.add('open');setTimeout(updateDictStatus,120)}",'open settings')
rep("applyVisualSettings();if(settings.autosave){const d=localStorage.getItem('dzenDraft');if(d)editor.value=d}syncSettingsUI();updateUserSynonymStatus();render();setTimeout(updateDictStatus,80);setTimeout(updateDictStatus,800);","applyVisualSettings();if(settings.autosave){const d=localStorage.getItem('dzenDraft');if(d)editor.value=d}syncSettingsUI();updateUserSynonymStatus();updateDzenRulesStatus();render();setTimeout(updateDictStatus,80);setTimeout(updateDictStatus,800);",'init')

p.write_text(s,encoding='utf-8')

g=Path('app/build.gradle')
b=g.read_text(encoding='utf-8')
if "versionCode 18" not in b or "versionName '1.3.5'" not in b:
    raise SystemExit('Unexpected Android version')
b=b.replace('versionCode 18','versionCode 19',1).replace("versionName '1.3.5'","versionName '1.4.0'",1)
g.write_text(b,encoding='utf-8')

m=Path('app/src/main/AndroidManifest.xml')
x=m.read_text(encoding='utf-8')
if 'android.permission.INTERNET' not in x:
    x=x.replace('<manifest xmlns:android="http://schemas.android.com/apk/res/android">','<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n    <uses-permission android:name="android.permission.INTERNET" />',1)
m.write_text(x,encoding='utf-8')
