plugins { id 'com.android.application' }

def keystorePath = System.getenv('ANDROID_KEYSTORE_PATH')
def keystoreAlias = System.getenv('ANDROID_KEY_ALIAS')
def keystorePassword = System.getenv('ANDROID_KEYSTORE_PASSWORD')
def keyPassword = System.getenv('ANDROID_KEY_PASSWORD')

android {
    namespace 'ru.dzenprep.texteditor'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.dzenprep.texteditor'
        minSdk 24
        targetSdk 35
        versionCode 15
        versionName '1.3.2'
    }

    signingConfigs {
        release {
  if (keystorePath) {
      storeFile file(keystorePath)
      storePassword keystorePassword
      keyAlias keystoreAlias
      keyPassword keyPassword
  }
        }
    }

    buildTypes {
        release {
  if (keystorePath) signingConfig signingConfigs.release
  minifyEnabled false
        }
    }
}
