plugins { id 'com.android.application' }

def keystorePath = System.getenv('ANDROID_KEYSTORE_PATH')
def keystoreAlias = System.getenv('ANDROID_KEY_ALIAS')
def keystorePassword = System.getenv('ANDROID_KEYSTORE_PASSWORD')
def keyPasswordValue = System.getenv('ANDROID_KEY_PASSWORD')

android {
    namespace 'ru.dzenprep.texteditor'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.dzenprep.texteditor'
        minSdk 24
        targetSdk 35
        versionCode 25
        versionName '1.6.1'
    }

    signingConfigs {
        release {
            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword keystorePassword
                keyAlias keystoreAlias
                keyPassword keyPasswordValue
            }
        }
    }

    buildTypes {
        release {
            if (keystorePath) signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
